// src/Utils/books.js
const books = [
  {
    id: 1,
    title: "Belajar JavaScript Dasar",
    author: "Andi Prasetyo",
    year: 2021,
    description: "Panduan lengkap pemula.",
    image: "https://placehold.co/150",
    price: "Rp 85.000",
  },
  {
    id: 2,
    title: "React untuk Pemula",
    author: "Dina Sari",
    year: 2022,
    description: "Konsep aplikasi modern",
    image: "https://placehold.co/150",
    price: "Rp 125.000",
  },
  {
    id: 3,
    title: "Paket kurir untuk Pemula",
    author: "Doni Kurir",
    year: 2023,
    description: "Panduan untuk kurir pemula",
    image: "https://placehold.co/150",
    price: "Rp 45.000",
  },
  {
    id: 4,
    title: "Mengasah Pedang",
    author: "Kevin Susanto",
    year: 2024,
    description: "Mengenal pedangmu lebih dalam",
    image: "https://placehold.co/150",
    price: "Rp 110.000",
  },
  {
    id: 5,
    title: "Rumah tingkat 3",
    author: "Riski Bilar",
    year: 2025,
    description: "Tutorial membangun rumah",
    image: "https://placehold.co/150",
    price: "Rp 500.000",
  },
  {
    id: 6,
    title: "C++ untuk pemula",
    author: "Juna Leri",
    year: 2026,
    description: "Belajar C++ dari dasar",
    image: "https://placehold.co/150",
    price: "Rp 95.000",
  },
  {
    id: 7,
    title: "Crosshair Placement",
    author: "Jack Gwane",
    year: 2027,
    description: "Cara penempatan crosshair dalam game",
    image: "https://placehold.co/150",
    price: "Rp 35.000",
  },
  {
    id: 8,
    title: "Build PC",
    author: "Angga Dewa",
    year: 2028,
    description: "Merakit PC dari 0",
    image: "https://placehold.co/150",
    price: "Rp 75.000",
  },
  {
    id: 9,
    title: "Resep makanan",
    author: "Michelle Loan",
    year: 2029,
    description: "Resep berbagai macam masakan",
    image: "https://placehold.co/150",
    price: "Rp 60.000",
  },
];

export default books;
